version: 2
updates:
  # Frontend Vue/Nuxt
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"

  # Backend NestJS
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"

  # Monitorar versões das GitHub Actions (.github/workflows)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
