// Project Sections - UI sections for project display
export { default as ActivityGraph } from './ActivityGraph.vue'
export { default as BacklogSection } from './BacklogSection.vue'
export { default as GoalsSection } from './GoalsSection.vue'
export { default as SmartObjectivesSection } from './SmartObjectivesSection.vue'
export { default as SmartDetailCard } from './SmartDetailCard.vue'
export { default as ProgressSection } from './ProgressSection.vue'
export { default as ProjectInfoCard } from './ProjectInfoCard.vue'
export { default as WBSTreeView } from './WBSTreeView.vue'
export { default as WBSTreeNode } from './WBSTreeNode.vue'
export { default as XMatrix } from './XMatrix.vue'
