import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsString, IsArray, IsOptional, IsNotEmpty } from 'class-validator';
import { ChecklistItemDto } from '../task/create-task.dto';
import { TaskDocument } from '../../schemas/task.schema';

export class CompletionFeedbackPayloadDto {
  @ApiPropertyOptional({
    description: 'Mensagem de celebração de conclusão da tarefa',
    example: 'Parabéns por concluir a tarefa!',
  })
  @IsString()
  @IsOptional()
  celebration?: string;

  @ApiPropertyOptional({
    description: 'Mensagem de validação das tarefas',
    example: 'Todos os itens foram concluídos.',
  })
  @IsString()
  @IsOptional()
  validation?: string;

  @ApiPropertyOptional({
    description: 'Pergunta reflexiva sobre a execução da tarefa',
    example: 'O que você achou de realizar essa atividade?',
  })
  @IsString()
  @IsOptional()
  question?: string;

  @ApiPropertyOptional({
    description: 'Lista de impedimentos encontrados durante a tarefa',
    example: ['Falta de internet', 'Complexidade imprevista'],
    type: [String],
  })
  @IsArray()
  @IsString({ each: true })
  @IsOptional()
  impediments?: string[];

  @ApiPropertyOptional({
    description: 'Passos selecionados para as próximas ações',
    example: ['Revisar documentação', 'Escrever testes unitários'],
    type: [String],
  })
  @IsArray()
  @IsString({ each: true })
  @IsOptional()
  selectedSteps?: string[];

  @ApiPropertyOptional({
    description: 'Ação executada',
    example: 'conclude',
  })
  @IsString()
  @IsOptional()
  action?: string;
}

export class GenerateFeedbackOnCompletionDto {
  @ApiProperty({ description: 'Instância do documento da tarefa concluída' })
  @IsNotEmpty()
  task!: TaskDocument;

  @ApiPropertyOptional({
    description: 'Checklist associado à tarefa (pode conter strings ou objetos ChecklistItemDto)',
    type: 'array',
    items: {
      type: 'object',
    },
  })
  @IsOptional()
  checklist?: Array<string | ChecklistItemDto>;

  @ApiPropertyOptional({ description: 'Tempo total gasto na execução em minutos', example: 50 })
  @IsOptional()
  timeSpentMinutes?: number;
}

export class CompletionFeedbackResult {
  @ApiProperty({ description: 'Celebration text generated by AI' })
  celebration!: string;

  @ApiProperty({ description: 'Validation analysis of completion' })
  validation!: string;

  @ApiProperty({ description: 'Question asking for reflection' })
  question!: string;

  @ApiProperty({ description: 'Suggestions or PDCA tips' })
  suggestion!: string;
}

export class CompletionFeedbackResponse {
  @ApiProperty({ description: 'Feedback text' })
  feedback!: string;

  @ApiProperty({ description: 'Feedback generation timestamp' })
  createdAt!: Date;
}

export class NextStepSuggestion {
  @ApiProperty({ description: 'Next step task title' })
  title!: string;

  @ApiProperty({ description: 'Next step task description' })
  description!: string;
}

export class SaveSuccessFeedbackDto {
  task!: TaskDocument;
  checklistSummary!: Array<{ item: string; completed: boolean }>;
  timeSpentMinutes?: number;
  feedbackObj!: CompletionFeedbackResult;
}

export class SaveErrorFeedbackOnCompletionDto {
  task!: TaskDocument;
  checklistSummary!: Array<{ item: string; completed: boolean }>;
  timeSpentMinutes?: number;
  error!: Error;
}
