@startuml Classes
skinparam style strictuml
left to right direction

class Task {
    _id: String 
    name: String
    description: String 
    pomodorosDid: Int
    pomodorosPlanned: Int
    deadline: Date
    priority: String 
    difficult: String
    project: String
    experience: Int
    isConcluded: Boolean
    late: Boolean
    prize: Int
    recurrency: String
    notification: Date
}

class Project {
    _id: String 
    name: String
    description: String
    color: String
    startDate: Date
    deadline: Date
    totalHoursWorked: Float
    plannedHours: Float
    shortTermGoal: String
    midTermGoal: String
    longTermGoal: String
    status: String
    progressPercentage: Float
}

class Habit {
    frequency : String
    description : String
    BeginDate : Date
    prize: Int
    penalty: Int
}

class User {
    money : Int
}

class Workout {
    Duration : String
    description : String
    days : String []
    frequency: String
    prize: Int
    penalty: Int
}

class Exercises {
    description : String
    repetition: Int
    weight: Float
    serie: Int
    equipment: String []
}

class Product {
    description : String
    value: Int
}

class DailyProgress {
    date: Date
    pomodorosDone: Int
    timeSpent: String
}

Task "1" -- "*" DailyProgress: track >
User "1" -- "*" Project: have a >
Project "1" -- "*" Task: have a >
User "1" -- "*" Habit: have a >
User "1" -- "*" Workout: have a >
Workout "1" -- "*" Exercises: have a >
User "1" -- "*" Product: buy a >
@enduml