export interface Task {
  _id: string
  name: string
  description?: string
  definitionOfDone?: string
  pomodorosDid?: number
  pomodorosPlanned: number
  pertOptimisticMinutes?: number
  pertMostLikelyMinutes?: number
  pertPessimisticMinutes?: number
  pertExpectedMinutes?: number
  pertVariance?: number
  requirementIds?: string[]
  rtmRisk?: boolean
  rtmRiskReason?: string
  evmProgress?: number
  evmPlannedValueMinutes?: number
  evmEarnedValueMinutes?: number
  evmSchedulePerformanceIndex?: number
  evmAlert?: string
  deadline: Date
  priority?: number
  difficult?: number
  project?: string
  parentWbsNodeId?: string
  wbsPath?: string
  generationBatchId?: string
  milestoneId?: string
  experience: number
  isConcluded: boolean
  late: boolean
  prize: number
  recurrency: string
  notification: Date
  microTaskType?: string
  cognitiveMode?: string
  contextTag?: string
  themeTag?: string[]
  createdAt?: Date
}
